version: "3.3"

volumes:
  local_postgres_data:
  static_volume:
  media_volume:

services:
  postgres_db:
    build:
      context: ./deploy/postgres
      dockerfile: Dockerfile
    container_name: hydrants_bot_db
    volumes:
      - ./deploy/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_postgres_data:/var/lib/postgresql/data:Z
    restart: always

  backend: &backend
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    container_name: hydrants_bot_backend
    depends_on:
      - postgres_db
    restart: always

