# Generated by Django 4.2.4 on 2023-09-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="Назва балансоутримувача"
                    ),
                ),
            ],
            options={
                "verbose_name": "Балансоутримувач",
                "verbose_name_plural": "Балансоутримувача",
            },
        ),
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Назва підрозділу"),
                ),
            ],
            options={
                "verbose_name": "Підрозділ",
                "verbose_name_plural": "Підроздили",
            },
        ),
        migrations.CreateModel(
            name="Hydrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        choices=[
                            ("несправний", "Несправний"),
                            ("справний", "Справний"),
                            ("зміщений", "Зміщений"),
                        ],
                        default="справний",
                        max_length=10,
                        verbose_name="Технічний стан",
                    ),
                ),
                (
                    "type_hydrant",
                    models.CharField(
                        choices=[
                            ("вулиичний", "Вуличний"),
                            ("об'єктовий", "Об'єктовий"),
                        ],
                        default="вулиичний",
                        max_length=10,
                        verbose_name="Тип гідранта",
                    ),
                ),
                (
                    "type_location",
                    models.CharField(
                        choices=[
                            ("підземний", "Підземний"),
                            ("надземний", "Надземний"),
                        ],
                        default="підземний",
                        max_length=10,
                        verbose_name="Вид розташування",
                    ),
                ),
                (
                    "type_water_network",
                    models.CharField(
                        choices=[("K", "K"), ("T", "K")],
                        max_length=1,
                        null=True,
                        verbose_name="Тип водомережі",
                    ),
                ),
                (
                    "type_diameter",
                    models.IntegerField(
                        choices=[
                            (20, "20"),
                            (40, "40"),
                            (50, "50"),
                            (65, "65"),
                            (70, "70"),
                            (75, "75"),
                            (76, "76"),
                            (80, "80"),
                            (86, "86"),
                            (100, "100"),
                            (102, "102"),
                            (110, "110"),
                            (120, "120"),
                            (125, "125"),
                            (150, "150"),
                            (160, "160"),
                            (175, "175"),
                            (180, "180"),
                            (200, "200"),
                            (219, "219"),
                            (222, "222"),
                            (225, "225"),
                            (250, "250"),
                            (273, "273"),
                            (300, "300"),
                            (315, "315"),
                            (320, "320"),
                            (325, "325"),
                            (350, "350"),
                            (400, "400"),
                            (500, "500"),
                            (600, "600"),
                        ],
                        verbose_name="Тип діаметра",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=1024, verbose_name="Прив'язка до адреси"
                    ),
                ),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "coordinates",
                    models.CharField(
                        max_length=256, verbose_name="Координати розташування"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hydrants",
                        to="hydrants.owner",
                    ),
                ),
                (
                    "subdivision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subdivision_hydrants",
                        to="hydrants.subdivision",
                    ),
                ),
            ],
        ),
    ]
