# Generated by Django 4.2.4 on 2023-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydrants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hydrant",
            options={"verbose_name": "Гідрант", "verbose_name_plural": "Гідрант"},
        ),
        migrations.AlterModelOptions(
            name="owner",
            options={
                "verbose_name": "Балансоутримувач",
                "verbose_name_plural": "Балансоутримувач",
            },
        ),
        migrations.AlterModelOptions(
            name="subdivision",
            options={"verbose_name": "Підрозділ", "verbose_name_plural": "Підрозділ"},
        ),
        migrations.AlterField(
            model_name="hydrant",
            name="coordinates",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Координати розташування"
            ),
        ),
    ]
