# Generated by Django 4.2.4 on 2023-10-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hydrants", "0003_hydrant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hydrants",
                to="hydrants.owner",
                verbose_name="Балансоутримувач",
            ),
        ),
        migrations.AlterField(
            model_name="hydrant",
            name="subdivision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subdivision_hydrants",
                to="hydrants.subdivision",
                verbose_name="Підрозділ",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Назва балансоутримувача"
            ),
        ),
    ]
