# Generated by Django 4.2.4 on 2023-10-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydrants", "0004_alter_hydrant_owner_alter_hydrant_subdivision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdivision",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Назва підрозділу"
            ),
        ),
    ]
