# Generated by Django 4.2.4 on 2023-10-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydrants", "0005_alter_subdivision_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hydrant",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="hydrant",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="hydrant",
            name="type_water_network",
            field=models.CharField(
                choices=[("K", "K"), ("T", "T")],
                max_length=1,
                null=True,
                verbose_name="Тип водомережі",
            ),
        ),
    ]
