# Generated by Django 4.2.4 on 2023-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydrants", "0006_hydrant_latitude_hydrant_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrant",
            name="latitude",
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="hydrant",
            name="longitude",
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
    ]
