# Generated by Django 4.2.4 on 2023-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydrants", "0007_alter_hydrant_latitude_alter_hydrant_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrant",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="hydrant",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
    ]
